---
- hosts: all
  become: true

  tasks:

  - name: install packages
    yum: name=httpd state=present
#     yum: name=httpd state=latest
  - name: start service
    service: name=httpd state=started enabled=yes